### ISSUE TITLE
Update formatting for Documentation

### ISSUE THREAD

**Issue by gavinjalberghini** [gavinjalberghini/Protein-Classification#1]
Clean up the general formatting. Have the document prepared in a way to add additional metrics easily.

**Comment by gavinjalberghini** [comment]
Made an initial pass at formatting the document. If there are any questions or comments on this topic please post it here.

**Comment by MichaelAFitzgerald** [comment]
It looks like everything has been updated for our report, I just have some last optimizations to do for the PROFEAT SVM model and then I'll push and update
